AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'Gemfile'
    - 'Rakefile'
  NewCops: enable
Layout/LineLength:
  Max: 100
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  IgnoredMethods: ['describe']
Metrics/MethodLength:
  Max: 15
Metrics/AbcSize:
  Max: 20
